lseek offset error
RT-Thread-packages/lwext4 pull request #7
Opened 2021-08-27 06:23 UTC by linzhenxing-bit

2021-08-27 13:21 UTC, mysterywolf requested changes
请确保 在修改的过程中，正常的rtt（非smart）也可以正常编译通过。

2021-08-27 13:22 UTC, mysterywolf requested changes
请确保 在修改的过程中，正常的rtt（非smart）也可以正常编译通过。

2021-08-27 13:22 UTC, mysterywolf commented on blockdev/rtthread/ext_blk_device.c
> +#include <rtdef.h>
rtthread.h里边已经有rtdef.h了，不需要再 include rtdef.h

2021-08-27 13:22 UTC, mysterywolf commented on blockdev/rtthread/dfs_ext.c
> +	rt_err_t result = -RT_EBUSY;
请注意 不要使用tab键 使用4个空格代替。

2021-08-28 20:50 UTC, mysterywolf requested changes

2021-08-28 20:50 UTC, mysterywolf commented on blockdev/rtthread/dfs_ext.c
> +        return -ENOENT;
此处不要改回来，我上次改回到RT_xxxx的
根据要求
返回值用RT_xxxx错误代码 带负号
errno用 ENOENT这种错误代码 不带负号

2021-08-30 01:42 UTC, linzhenxing-bit commented on blockdev/rtthread/dfs_ext.c
> +        return -ENOENT;
好的，应该是失误修改了

2021-08-30 01:51 UTC, mysterywolf commented
感谢提交pr 😊

2021-08-30 01:52 UTC, merged